### ISSUE TITLE
Add GetUnitsByAPCount

### ISSUE THREAD

**Issue by dadav** [evilsocket/pwngrid#2]
Wouldn't it be a nice idea to have a list of the top units and show them in the pwnagotchi.ai page (Top Units)? It would be super encouraging for the users.

**Comment by evilsocket** [comment]
I thought about it, however there's one big catch: the API is open, and anybody with valid RSA keys can report as many APs they want. If we create an incentive for competition, we create an incentive for people to send fake data we can't verify server side. So what's the point? That is why I thought the only way to have some sort of competition, would be to upload /root/brain.nn server side where I can run simulations and see on average how the neural networks perform.

**Comment by dadav** [comment]
Shit, i forgot that ppl. are evil :D Ok, your competition idea seems cooler anyway ^.^

**Comment by evilsocket** [comment]
i've been thinking about these problematics for months :D
